services:
  config-server:
    build: ./config-server
    container_name: config-server
    environment:
      - CONFIG_USERNAME=${CONFIG_USERNAME}
      - CONFIG_TOKEN=${CONFIG_TOKEN}
    ports:
      - 8888:8888
    networks:
      - global
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 8

  rabbitmq1:
    image: rabbitmq:3-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - ${PWD}/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ${PWD}/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - rabbitmq1-data:/var/lib/rabbitmq/
      - rabbitmq1-logs:/var/log/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - global
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  rabbitmq2:
    image: rabbitmq:3-management
    container_name: rabbitmq2
    hostname: rabbitmq2
    depends_on:
      rabbitmq1:
        condition: service_healthy
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - ${PWD}/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ${PWD}/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - rabbitmq2-data:/var/lib/rabbitmq/
      - rabbitmq2-logs:/var/log/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - global
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  rabbitmq3:
    image: rabbitmq:3-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    depends_on:
      rabbitmq1:
        condition: service_healthy
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - ${PWD}/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ${PWD}/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - rabbitmq3-data:/var/lib/rabbitmq/
      - rabbitmq3-logs:/var/log/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    networks:
      - global
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  haproxy:
    image: haproxy:1.7
    volumes:
      - ${PWD}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      rabbitmq1:
        condition: service_healthy
      rabbitmq2:
        condition: service_healthy
      rabbitmq3:
        condition: service_healthy
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - global

  eureka-server:
    build: ./eureka
    container_name: eureka-server
    ports:
      - 8761:8761
    depends_on:
      config-server:
        condition: service_healthy
      haproxy:
        condition: service_started
    environment:
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI:-http://config-server:8888}
    networks:
      - global
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 8

  user-service-db:
    image: postgres:17
    container_name: user-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: user_service
    ports:
      - 5433:5432
    volumes:
      - user_service_data:/var/lib/postgresql/data
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - global
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI:-http://config-server:8888}
    ports: []
    depends_on:
      user-service-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      rabbitmq1:
        condition: service_healthy
    networks:
      - global

  spacecraft-service-db:
    image: postgres:17
    container_name: spacecraft-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: spacecraft_service
    ports:
      - 5434:5432
    volumes:
      - spacecraft_service_data:/var/lib/postgresql/data
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - global
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  spacecraft-service:
    build: ./spacecraft-service
    container_name: spacecraft-service
    environment:
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI:-http://config-server:8888}
    ports: []
    depends_on:
      spacecraft-service-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      rabbitmq1:
        condition: service_healthy
    networks:
      - global

  cargo-service-db:
    image: postgres:17
    container_name: cargo-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: cargo_service
    ports:
      - 5435:5432
    volumes:
      - cargo_service_data:/var/lib/postgresql/data
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - global
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  cargo-service:
    build: ./cargo-service
    container_name: cargo-service
    environment:
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI:-http://config-server:8888}
    ports: []
    depends_on:
      cargo-service-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      rabbitmq1:
        condition: service_healthy
    networks:
      - global

  mission-service-db:
    image: postgres:17
    container_name: mission-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: mission_service
    ports:
      - 5436:5432
    volumes:
      - mission_service_data:/var/lib/postgresql/data
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - global
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  mission-service:
    build: ./mission-service
    container_name: mission-service
    environment:
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI:-http://config-server:8888}
    ports: []
    depends_on:
      mission-service-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      rabbitmq1:
        condition: service_healthy
    networks:
      - global

  maintenance-service-db:
    image: postgres:17
    container_name: maintenance-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: maintenance_service
    ports:
      - 5437:5432
    volumes:
      - maintenance_service_data:/var/lib/postgresql/data
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - global
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  maintenance-service:
    build: ./maintenance-service
    container_name: maintenance-service
    environment:
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI:-http://config-server:8888}
    ports: []
    depends_on:
      maintenance-service-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      rabbitmq1:
        condition: service_healthy
    networks:
      - global

  inventory-service-db:
    image: postgres:17
    container_name: inventory-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: inventory_service
    ports:
      - 5438:5432
    volumes:
      - inventory_service_data:/var/lib/postgresql/data
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - global
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    environment:
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI:-http://config-server:8888}
    ports: []
    depends_on:
      inventory-service-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      rabbitmq1:
        condition: service_healthy
    networks:
      - global

  message-producer-service:
    build: ./message-producer-service
    container_name: message-producer-service
    environment:
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI:-http://config-server:8888}
    ports:
      - 8087:8087
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      rabbitmq1:
        condition: service_healthy
    networks:
      - global

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - 8080:8080
    depends_on:
      - user-service
      - spacecraft-service
      - cargo-service
      - mission-service
      - maintenance-service
      - inventory-service
    networks:
      - global
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 8

volumes:
  user_service_data:
  spacecraft_service_data:
  cargo_service_data:
  mission_service_data:
  maintenance_service_data:
  inventory_service_data:
  rabbitmq1-data:
  rabbitmq1-logs:
  rabbitmq2-data:
  rabbitmq2-logs:
  rabbitmq3-data:
  rabbitmq3-logs:

networks:
  global:
    driver: bridge
