services:
  config-server:
    build: ./config-server
    container_name: config-server
    environment:
      - CONFIG_USERNAME=${CONFIG_USERNAME}
      - CONFIG_TOKEN=${CONFIG_TOKEN}
    ports:
      - 8888:8888
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 8

  kafka-1:
    image: apache/kafka:latest
    container_name: kafka-1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - 9092:9092
    volumes:
      - kafka-1-data:/var/lib/kafka/data
    restart: unless-stopped

  kafka-2:
    image: apache/kafka:latest
    container_name: kafka-2
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - kafka-2-data:/var/lib/kafka/data
    restart: unless-stopped

  kafka-3:
    image: apache/kafka:latest
    container_name: kafka-3
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9093,2@kafka-2:9093,3@kafka-3:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - kafka-3-data:/var/lib/kafka/data
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minio}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minio123}
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9001/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio-init:
    image: minio/minio
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minio}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minio123}
    volumes:
      - ./init/minio:/init:z
    entrypoint: [ "/bin/sh", "/init/init.sh" ]
    restart: "no"

  file-service:
    build: ./file-service
    container_name: file-service
    environment:
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI:-http://config-server:8888}
    ports: [ ]
    depends_on:
      minio:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 8

  eureka-server:
    build: ./eureka
    container_name: eureka-server
    ports:
      - 8761:8761
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI:-http://config-server:8888}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 8

  user-service-db:
    image: postgres:17
    container_name: user-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: user_service
    ports:
      - 5433:5432
    volumes:
      - user_service_data:/var/lib/postgresql/data
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI:-http://config-server:8888}
    ports: []
    depends_on:
      user-service-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  spacecraft-service-db:
    image: postgres:17
    container_name: spacecraft-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: spacecraft_service
    ports:
      - 5434:5432
    volumes:
      - spacecraft_service_data:/var/lib/postgresql/data
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  spacecraft-service:
    build: ./spacecraft-service
    container_name: spacecraft-service
    environment:
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI:-http://config-server:8888}
    ports: []
    depends_on:
      spacecraft-service-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  cargo-service-db:
    image: postgres:17
    container_name: cargo-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: cargo_service
    ports:
      - 5435:5432
    volumes:
      - cargo_service_data:/var/lib/postgresql/data
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  cargo-service:
    build: ./cargo-service
    container_name: cargo-service
    environment:
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI:-http://config-server:8888}
    ports: []
    depends_on:
      cargo-service-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  mission-service-db:
    image: postgres:17
    container_name: mission-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: mission_service
    ports:
      - 5436:5432
    volumes:
      - mission_service_data:/var/lib/postgresql/data
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  mission-service:
    build: ./mission-service
    container_name: mission-service
    environment:
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI:-http://config-server:8888}
    ports: []
    depends_on:
      mission-service-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  maintenance-service-db:
    image: postgres:17
    container_name: maintenance-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: maintenance_service
    ports:
      - 5437:5432
    volumes:
      - maintenance_service_data:/var/lib/postgresql/data
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  maintenance-service:
    build: ./maintenance-service
    container_name: maintenance-service
    environment:
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI:-http://config-server:8888}
    ports: []
    depends_on:
      maintenance-service-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  inventory-service-db:
    image: postgres:17
    container_name: inventory-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: inventory_service
    ports:
      - 5438:5432
    volumes:
      - inventory_service_data:/var/lib/postgresql/data
    depends_on:
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    environment:
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI:-http://config-server:8888}
    ports: []
    depends_on:
      inventory-service-db:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  message-producer-service:
    build: ./message-producer-service
    container_name: message-producer-service
    environment:
      - CONFIG_SERVER_URI=${CONFIG_SERVER_URI:-http://config-server:8888}
    ports:
      - 8087:8087
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - 8080:8080
    depends_on:
      - eureka-server
      - config-server
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 8

volumes:
  user_service_data:
  spacecraft_service_data:
  cargo_service_data:
  mission_service_data:
  maintenance_service_data:
  inventory_service_data:
  minio-data:
  kafka-1-data:
  kafka-2-data:
  kafka-3-data: