server:
  port: 0

spring:
  application:
    name: maintenance-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://config-server:8888}
  cloud:
    config:
      fail-fast: true
      allow-override: true
      retry:
        max-attempts: 20
        initial-interval: 3000
jwt:
  secret-key: "fbuVwHzCoJrhyC0UvnMeq8B6GXQ36uaqWKrb8a7Ch0Y"