server:
  port: 0  # Динамический порт для Eureka

spring:
  application:
    name: inventory-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://config-server:8888}
  cloud:
    config:
      fail-fast: true
      allow-override: true  
      retry:
        max-attempts: 20
        initial-interval: 3000

