server:
  port: 0  # Динамический порт для Eureka

spring:
  application:
    name: inventory-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://config-server:8888}
  cloud:
    config:
      fail-fast: true
      allow-override: true  
      retry:
        max-attempts: 20
        initial-interval: 3000

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    enabled: true
    instances:
      userService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s
      spacecraftService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 15s  # Дольше ждем перед повторной попыткой
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 30      # Более строгий порог ошибок
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 5s
      cargoService:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 15s  # Дольше ждем перед повторной попыткой
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 30      # Более строгий порог ошибок
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 5s
  
  # Добавляем Rate Limiter
  ratelimiter:
    enabled: true
    instances:
      spacecraftService:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0
