server:
  port: 8087

spring:
  application:
    name: message-producer-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://config-server:8888}
  cloud:
    config:
      fail-fast: true
      allow-override: true
      retry:
        max-attempts: 20
        initial-interval: 3000
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq1}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

